spring.application.name=apache-camel-pp-1
camel.main.run-controller=true

app.file.input-dir=input
app.file.max-text-size=10240

app.kafka.topic=text-files
camel.component.kafka.brokers=localhost:9092
app.api.upload-url=http://localhost:8081/upload

